"""add field general_attendances_count to daily_report

Revision ID: 5ee95176e825
Revises: 5be69cb03a15
Create Date: 2024-09-13 11:25:49.069022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ee95176e825'
down_revision: Union[str, None] = '5be69cb03a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_report', sa.Column('general_attendances_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_report', 'general_attendances_count')
    # ### end Alembic commands ###
