"""add field general to daily_report

Revision ID: cc10b4b3e62a
Revises: 270fe02feed9
Create Date: 2024-09-09 17:47:58.265318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc10b4b3e62a'
down_revision: Union[str, None] = '270fe02feed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_report', sa.Column('general', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_report', 'general')
    # ### end Alembic commands ###
